### ISSUE TITLE
Report not loaded because it does not contain any data with schema http://hyperfoil.io/run-schema/v2.0

### ISSUE THREAD

**Issue by eguzki** [Hyperfoil/hyperfoil_test#11]
I am running into this issue when running tests:

![Screenshot_2021-04-23 HF report](https://user-images.githubusercontent.com/881529/115793005-9f3a0380-a3cb-11eb-93a1-cab1ec6854f1.png)

Running `hyperfoil_version: 0.15`

Used task from https://github.com/3scale-labs/perftest-toolkit/blob/master/deployment/run.yml:
```
- hosts: hyperfoil_controller                
  roles:                                     
    - hyperfoil.hyperfoil_test               
  vars:                                      
    test_name: 3scale-benchmark              
    test_files:                              
      - "{{ csv_dest_file_path }}"           
    shared_connections: 10                   
    users_per_sec: 10                        
    duration_sec: 30                         
```

I see from [Release notes](https://hyperfoil.io/docs/release_notes.html) that release  0.15 changed Report schema to v3.0

**Comment by rvansa** [comment]
Hi @eguzki , yes, we've done some changes to the schema and had to bump up the version. How exactly do you obtain the report? It seems that you're using wrong template; when you create the report using matching version of CLI or through WebCLI it should pick up a new template https://hyperfoil.io/report-template-v3.0.html#/

**Comment by eguzki** [comment]
Using these ansible tasks:
```
# role task file for hyperfoil_generate_report
---
- name: Reports directory
  file:
    state: directory
    path: "{{ reports_path }}"
    recurse: yes
    mode: '0755'
- name: Retrieve the run data
  get_url:
    url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/run/{{ test_runid }}/stats/all"
    headers:
      Accept: 'application/json'
    dest: "{{ reports_path }}/{{ test_runid }}-all.json"
- name: Creates hyperfoil report
  docker_container:
    name: hyperfoil_report
    state: started
    tty: True
    detach: no
    image: quay.io/hyperfoil/hyperfoil-report
    command: "bash -c \"/opt/report.sh /tmp/reports/{{ test_runid }}-all.json > /tmp/reports/index-{{ test_runid }}.html\""
    volumes:
      - "{{ reports_path }}:/tmp/reports:z"
```

**Comment by eguzki** [comment]
I guess I need to update my benchmark definition yaml:
```
name: 3scale-benchmark
agents:
{% for agent in groups[hyperfoil_agent_group] %}
  {{ agent }}: {{ hostvars[agent]['ansible_host'] }}:{{ hyperfoil_agent_port }}
{% endfor %}
http:
{% for host in groups[injector_target_group] %}
- host: {{ injector_hyperfoil_target_protocol }}://{{ host }}:{{ injector_hyperfoil_target_port }}
  sharedConnections: {{ shared_connections }}
{% endfor %}
usersPerSec: {{ users_per_sec }}
duration: {{ duration_sec }}s
maxDuration: {{ duration_sec }}s
scenario:
- testSequence:
  - randomCsvRow:
     file: {{ csv_dest_file_path }}
     skipComments: 'True'
     removeQuotes: 'True'
     columns:
       0: target-host
       1: uri
  - template:
      pattern: ${target-host}:{{ injector_hyperfoil_target_port }}
      toVar: target-authority
  - httpRequest:
      authority:
        fromVar: target-authority
      GET:
        fromVar: uri
      headers:
        HOST:
          fromVar: target-host

threads: {{ injector_hyperfoil_agent_threads }}
```
